### ISSUE TITLE
creating a pdf of markdown files

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara_research#12]
Could you provide a method to create a pdf from a markdown file that shows nicely formatted equations? The idea is to have a way for students to submit their assignments in a nicely formatted way. I know there was discussion of this, but I can't find the documentation of how to do this. I'll need to link to that documentation (once it exists) from the course websites where I define assignments.

**Comment by fletchapin** [comment]
@monroews I'm looking into this now and our current sync-settings have a package which converts from markdown to PDF which can be done using ```ctrl + shift + c```.

However, that option doesn't format LaTeX equations nicely, so I'm looking into other alternatives and when I find the easiest one that works well I can put a short document together outlining how to do the conversion.

**Comment by ethan92429** [comment]
I'm exploring using [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced/graphs/code-frequency) instead of markdown-preview-plus. They appear to be competing markdown packages. MPE supports directly exporting the PDF AND has the same keybindings as MPP. Just right click on the preview and select "open in browser" - then just print to PDF from the browser.

**Comment by ethan92429** [comment]
I've updated the sync settings to reflect this. So if you fork again, you'll pull the right packages.

**Comment by fletchapin** [comment]
Added [the tutorial](https://github.com/AguaClara/aguaclara_tutorial/wiki/Tutorial:-Saving-a-Markdown-File-as-a-PDF) to the wiki page of the aguaclara_tutorial repo.
